apiVersion: v1
kind: Service
metadata:
  name: gitbook
spec:
  type: NodePort
  ports:
    - port: 4000
      name: port
      protocol: TCP
      targetPort: 4000
      nodePort: 30000
    - port: 35731
      name: lrport
      protocol: TCP
      targetPort: 35731
  selector:
    app: gitbook

